version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: inallmedia-postgres
    environment:
      POSTGRES_DB: challengeDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
    ports:
      - "5434:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - inallmedia-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: inallmedia-app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://inallmedia-postgres:5432/challengeDB
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
    networks:
      - inallmedia-network

networks:
  inallmedia-network:
    driver: bridge

volumes:
  postgres-data: